### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by rocket-hub** [tinic/pendant2020#2]
Hi tinic I need your contact to solve a problem on esp32 artnet node
I would be very grateful to you 
thank you

**Comment by tinic** [comment]
What's your issue?

**Comment by rocket-hub** [comment]
i am using an esp32 only wi-fi,
I modified your code:
false, // dhcpEnable
   true, // standAloneEnable
   false, // ethernetEnable

starts in hot spots, everything ok,
but once configured in the web interface with ssid and password it always starts in hot spot mode ...
can you help me configure your code to use esp32 in wi-fi mode?
thank you very much

**Comment by tinic** [comment]
false, // dhcpEnable
   **false**, // standAloneEnable
   false, // ethernetEnable

standAloneEnable set to true will enable the hot spot mode. Setting this to false should work.

See code here:

1846> if (deviceSettings.standAloneEnable) {
1847>    startHotspot();

**Comment by tinic** [comment]
The other reason it could start a hotspot is if the SSID somehow did not get set properly. It would be useful to see what the Arduino serial output says.

**Comment by rocket-hub** [comment]
false, // dhcpEnable
  false, // standAloneEnable
  false, // ethernetEnable
I set it up like you said


rst: 0xc (SW_CPU_RESET), boot: 0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP: 0xee
clk_drv: 0x00, q_drv: 0x00, d_drv: 0x00, cs0_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00
mode: GOD, clock div: 1
load: 0x3fff0018, len: 4
load: 0x3fff001c, len: 1216
I have 0 tail 12 room 4
load: 0x40078000, len: 9720
I have 0 tail 12 room 4
load: 0x40080400, len: 6352
entry 0x400806b8
dhcps: send_offer >> udp_sendto result 0
Guru Meditation Error: Core 0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC: 0x00000000 PS: 0x00060230 A0: 0x80127729 A1: 0x3ffb4e80
A2: 0x3ffdc590 A3: 0x3ffdc814 A4: 0x3ffdc2b0 A5: 0x3ffdbe90
A6: 0x0204a8c0 A7: 0x6504a8c0 A8: 0x801275cc A9: 0x3ffb4e40
A10: 0x3ffdc5a0 A11: 0x3ffdc814 A12: 0x3ffb4e8c A13: 0x00000044
A14: 0x00000001 A15: 0x00000006 SAR: 0x00000010 EXCCAUSE: 0x00000014
EXCVADDR: 0x00000000 LBEG: 0x4000c349 LEND: 0x4000c36b LCOUNT: 0x00000000

Backtrace: 0x00000000: 0x3ffb4e80 0x40127726: 0x3ffb4ec0 0x401345ad: 0x3ffb4ee0 0x401395b5: 0x3ffb4f20 0x4013e852: 0x3ffb4f40 0x4012812f: 0x3ffb4f460

Rebooting ...
ets Jun 8 2016 00:22:57

rst: 0xc (SW_CPU_RESET), boot: 0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP: 0xee
clk_drv: 0x00, q_drv: 0x00, d_drv: 0x00, cs0_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00
mode: GOD, clock div: 1
load: 0x3fff0018, len: 4
load: 0x3fff001c, len: 1216
I have 0 tail 12 room 4
load: 0x40078000, len: 9720
I have 0 tail 12 room 4
load: 0x40080400, len: 6352
entry 0x400806b8
dhcps: send_offer >> udp_sendto result 0
Guru Meditation Error: Core 0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC: 0x00000000 PS: 0x00060e30 A0: 0x80127729 A1: 0x3ffb4e80
A2: 0x3ffdc57c A3: 0x3ffddc48 A4: 0x3ffdc29c A5: 0x3ffdbe7c
A6: 0x0204a8c0 A7: 0x6504a8c0 A8: 0x801275cc A9: 0x3ffb4e40
A10: 0x3ffdc58c A11: 0x3ffddc48 A12: 0x3ffb4e8c A13: 0x00000044
A14: 0x00000001 A15: 0x00000006 SAR: 0x00000010 EXCCAUSE: 0x00000014
EXCVADDR: 0x00000000 LBEG: 0x4000c349 LEND: 0x4000c36b LCOUNT: 0x00000000

Backtrace: 0x00000000: 0x3ffb4e80 0x40127726: 0x3ffb4ec0 0x401345ad: 0x3ffb4ee0 0x401395b5: 0x3ffb4f20 0x4013e852: 0x3ffb4f40 0x4012812f: 0x3ffb4f460

Rebooting ...
ets Jun 8 2016 00:22:57

rst: 0xc (SW_CPU_RESET), boot: 0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP: 0xee
clk_drv: 0x00, q_drv: 0x00, d_drv: 0x00, cs0_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00
mode: GOD, clock div: 1
load: 0x3fff0018, len: 4
load: 0x3fff001c, len: 1216
I have 0 tail 12 room 4
load: 0x40078000, len: 9720
I have 0 tail 12 room 4
load: 0x40080400, len: 6352
entry 0x400806b8
dhcps: send_offer >> udp_sendto result 0
Guru Meditation Error: Core 0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC: 0x00000000 PS: 0x00060e30 A0: 0x80127729 A1: 0x3ffb4e80
A2: 0x3ffdbb20 A3: 0x3ffdcc3c A4: 0x3ffdc294 A5: 0x3ffdbe74
A6: 0x0204a8c0 A7: 0x6504a8c0 A8: 0x801275cc A9: 0x3ffb4e40
A10: 0x3ffdbb30 A11: 0x3ffdcc3c A12: 0x3ffb4e8c A13: 0x00000044
A14: 0x00000001 A15: 0x00000006 SAR: 0x00000010 EXCCAUSE: 0x00000014
EXCVADDR: 0x00000000 LBEG: 0x4000c349 LEND: 0x4000c36b LCOUNT: 0x00000000

Backtrace: 0x00000000: 0x3ffb4e80 0x40127726: 0x3ffb4ec0 0x401345ad: 0x3ffb4ee0 0x401395b5: 0x3ffb4f20 0x4013e852: 0x3ffb4f40 0x4012812f: 0x3ffb4f460

Rebooting ...
ets Jun 8 2016 00:22:57

rst: 0xc (SW_CPU_RESET), boot: 0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP: 0xee
clk_drv: 0x00, q_drv: 0x00, d_drv: 0x00, cs0_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00
mode: GOD, clock div: 1
load: 0x3fff0018, len: 4
load: 0x3fff001c, len: 1216
I have 0 tail 12 room 4
load: 0x40078000, len: 9720
I have 0 tail 12 room 4
load: 0x40080400, len: 6352
entry 0x400806b8
dhcps: send_offer >> udp_sendto result 0
Guru Meditation Error: Core 0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC: 0x00000000 PS: 0x00060030 A0: 0x80127729 A1: 0x3ffb4e80
A2: 0x3ffdd8a0 A3: 0x3ffddad4 A4: 0x3ffdb2d4 A5: 0x3ffdc338
A6: 0x0204a8c0 A7: 0x6504a8c0 A8: 0x801275cc A9: 0x3ffb4e40
A10: 0x3ffdd8b0 A11: 0x3ffddad4 A12: 0x3ffb4e8c A13

 but it doesn't let me access the web page

**Comment by rocket-hub** [comment]
I did several tests but it always starts in the hot spot, it cannot access ... I am trying the same code on esp8266 and it works, so the wi fi is not the problem ...

**Comment by tinic** [comment]
Looks like you are crashing for some reason. ESP32 is quite different from the esp8266 since two threads are running. I'll take a look later tonight to see if I can repro with my ESP32 device(s).

**Comment by rocket-hub** [comment]
thank you so much for your help
I really need it for a work project
I hope I can make it work
Thanks again!

**Comment by rocket-hub** [comment]
Hello
I did some tests with an olimex esp32-poe-iso board, the wifi part seems to work ...
while ethernet gives me this error:
"E (1166) emac: Timed out waiting for PHY register 0x2 to have value 0x0007 (mask 0xffff). Current value 0xffff
E (2166) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0 (mask 0xfff0). Current value 0xffff
E (2166) emac: Initialise PHY device Timeout "
do you know him? how did you solve? seems like a common problem of olimex ...
While with other boards esp32 does not connect to wifi, I did a lot of tests, I think the problem is related to the partitions:
"esp32 E (146) SPIFFS: mount failed, -10025"
but I'm not sure ...
Why with olimex yes and with esp32 generic board no?
sorry for disturbing
thank you
